trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ci
      source: ci
      trigger: true

variables:
  serviceConnection: 'azure-sp'
  artifactName: 'drop'
  slotHealthUrl: '/health'
  timeoutInSeconds: 30

stages:
# =====================================================
#  DEV 
# =====================================================
- stage: Dev
  displayName: Deploy to DEV
  jobs:
  - deployment: DevDeploy
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          # Download CI artifact
          - download: ci
            artifact: $(artifactName)

          # Terraform Init
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: latest

          - task: TerraformCLI@1
            displayName: Terraform Init
            inputs:
              command: init
              workingDirectory: infra/dev

          - task: TerraformCLI@1
            displayName: Terraform Apply
            inputs:
              command: apply
              workingDirectory: infra/dev
              environmentServiceName: $(serviceConnection)
              args: '-auto-approve'

          # Deploy ZIP to blue slot
          - task: AzureWebApp@1
            displayName: Deploy to DEV (blue slot)
            inputs:
              azureSubscription: $(serviceConnection)
              appName: 'poc-api-dev'
              package: '$(Pipeline.Workspace)/ci/$(artifactName)/*.zip'
              slotName: 'blue'

# =====================================================
#  STAGING 
# =====================================================
- stage: Staging
  dependsOn: Dev
  displayName: Deploy to STAGING
  jobs:
  - deployment: StagingDeploy
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - download: ci
            artifact: $(artifactName)

          # Terraform
          - task: TerraformInstaller@1
          - task: TerraformCLI@1
            displayName: Terraform Init
            inputs:
              command: init
              workingDirectory: infra/staging

          - task: TerraformCLI@1
            displayName: Terraform Apply
            inputs:
              command: apply
              workingDirectory: infra/staging
              environmentServiceName: $(serviceConnection)
              args: '-auto-approve'

          # Deploy ZIP to green slot
          - task: AzureWebApp@1
            displayName: Deploy to STAGING (green slot)
            inputs:
              azureSubscription: $(serviceConnection)
              appName: 'poc-api-staging'
              package: '$(Pipeline.Workspace)/ci/$(artifactName)/*.zip'
              slotName: 'green'

# =====================================================
#  PROD  (Blue/Green)
# =====================================================
- stage: Prod
  dependsOn: Staging
  displayName: Deploy to PROD (Blue/Green)
  jobs:
  - deployment: ProdDeploy
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - download: ci
            artifact: $(artifactName)

          # Terraform
          - task: TerraformInstaller@1

          - task: TerraformCLI@1
            displayName: Terraform Init
            inputs:
              command: init
              workingDirectory: infra/prod

          - task: TerraformCLI@1
            displayName: Terraform Apply
            inputs:
              command: apply
              workingDirectory: infra/prod
              environmentServiceName: $(serviceConnection)
              args: '-auto-approve'

          # Deploy ZIP to green slot
          - task: AzureWebApp@1
            displayName: Deploy to PROD (GREEN slot)
            inputs:
              azureSubscription: $(serviceConnection)
              appName: 'poc-api-prod'
              package: '$(Pipeline.Workspace)/ci/$(artifactName)/*.zip'
              slotName: 'green'

          # -------------------------------
          # Health Check on GREEN slot
          # -------------------------------
          - script: |
              echo "Checking health on green slot..."
              for i in {1..10}; do
                STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://poc-api-prod-green.azurewebsites.net$(slotHealthUrl)")
                echo "Attempt $i -> HTTP $STATUS"
                if [ "$STATUS" = "200" ]; then
                  echo "GREEN slot healthy."
                  exit 0
                fi
                sleep 5
              done
              echo "ERROR: GREEN slot health check failed."
              exit 1
            displayName: Health Check

          # -------------------------------
          # Swap GREEN → PRODUCTION
          # -------------------------------
          - task: AzureAppServiceManage@0
            displayName: Swap GREEN slot to PROD
            inputs:
              azureSubscription: $(serviceConnection)
              WebAppName: 'poc-api-prod'
              ResourceGroupName: 'rg-poc-prod'
              SourceSlot: 'green'
              SwapWithProduction: true

          - script: echo "Deployment to PROD completed successfully."
            displayName: Success Summary
