
CREATE TABLE IF NOT EXISTS Data_Office
(desk_id INT NOT NULL,
chairDirection VARCHAR(50) NOT NULL,
x int NOT NULL,
y int NOT NULL,
PRIMARY KEY(desk_id)
);

CREATE TABLE equipments(
   id INT GENERATED ALWAYS AS IDENTITY,
   desk_id INT,
   type VARCHAR(50) NOT NULL,
   specification VARCHAR(100),
   PRIMARY KEY(id),
   CONSTRAINT fk_DataOffice
      FOREIGN KEY(desk_id) 
	  REFERENCES Data_Office(desk_id)
);

INSERT INTO Data_Office (desk_id, chairDirection, x, y)
VALUES ('1', 'south', 0, 0),
 ('2', 'south', 1, 0),
 ('3', 'south', 2, 0),
 ('4', 'south', 3, 0),
 ('5', 'south', 0, 1),
 ('6', 'south', 1, 1),
 ('7', 'south', 2, 1),
 ('8', 'south', 3, 1),
 ('9', 'south', 0, 2),
 ('10', 'south', 1, 2),
 ('11', 'south', 2, 2),
 ('12', 'south', 3, 2);


 INSERT INTO equipments (desk_id, type, specification)
VALUES ('1', 'desk', 'Simple desk'),
 ('1', 'laptop', 'Laptop Dell Inspiron 15 5000'),
 ('1', 'phone', 'Cisco Phone IP 7960G/7940G'),
 ('1', 'chair', '817L Kare Ergonomic Office Chair'),
 ('1', 'drawer', 'Simple drawer'),
 ('2', 'desk', 'Simple desk'),
 ('2', 'cpu', 'Dual core 2.4 GHz, 16 GB RAM, 256 GB HD'),
 ('2', 'monitor', 'HP V197 18.5-inch'),
 ('2', 'keyboard', 'HP Ultrathin Wireless Keyboard'),
 ('2', 'phone', 'Cisco Phone IP 7960G/7940G'),
 ('2', 'chair', '817L Kare Ergonomic Office Chair'),
 ('2', 'mouse', 'HP USB 2 Button Optical Mouse'),
 ('2', 'drawer', 'Simple drawer'),
 ('3', 'desk', 'Simple desk'),
 ('3', 'cpu', 'Dual core 2.4 GHz, 16 GB RAM, 256 GB HD'),
 ('3', 'monitor', 'HP V197 18.5-inch'),
 ('3', 'keyboard', 'HP Ultrathin Wireless Keyboard'),
 ('3', 'chair', '817L Kare Ergonomic Office Chair'),
 ('3', 'mouse', 'HP USB 2 Button Optical Mouse'),
 ('3', 'drawer', 'Simple drawer'),
 ('4', 'desk', 'Simple desk'),
 ('4', 'chair', '817L Kare Ergonomic Office Chair'),
 ('4', 'laptop', 'Laptop Dell Inspiron 15 5000'),
 ('4', 'phone', 'Cisco Phone IP 7960G/7940G'),
 ('4', 'drawer', 'Simple drawer'),
 ('5', 'desk', 'Simple desk'),
 ('5', 'chair', '817L Kare Ergonomic Office Chair'),
 ('5', 'laptop', 'Laptop Dell Inspiron 15 5000'),
 ('5', 'drawer', 'Simple drawer'),
 ('6', 'desk', 'Simple desk'),
 ('6', 'chair', '817L Kare Ergonomic Office Chair'),
 ('6', 'drawer', 'Simple drawer'),
 ('7', 'desk', 'Simple desk'),
 ('7', 'cpu', 'Dual core 2.4 GHz, 16 GB RAM, 256 GB HD'),
 ('7', 'monitor', 'HP V197 18.5-inch'),
 ('7', 'keyboard', 'HP Ultrathin Wireless Keyboard'),
 ('7', 'phone', 'Cisco Phone IP 7960G/7940G'),
 ('7', 'chair', '817L Kare Ergonomic Office Chair'),
 ('7', 'mouse', 'HP USB 2 Button Optical Mouse'),
 ('7', 'drawer', 'Simple drawer'),
 ('8', 'desk', 'Simple desk'),
 ('8', 'laptop', 'Laptop Dell Inspiron 15 5000'),
 ('8', 'chair', '817L Kare Ergonomic Office Chair'),
 ('9', 'desk', 'Simple desk'),
 ('9', 'chair', '817L Kare Ergonomic Office Chair'),
 ('9', 'drawer', 'Simple drawer'),
 ('10', 'desk', 'Simple desk'),
 ('10', 'monitor', 'HP V197 18.5-inch'),
 ('10', 'desktop', 'HP CPU, keyboard and mouse'),
 ('10', 'phone', 'Cisco Phone IP 7960G/7940G'),
 ('10', 'chair', '817L Kare Ergonomic Office Chair'),
 ('10', 'drawer', 'Simple drawer'),
 ('11', 'desk', 'Simple desk'),
 ('11', 'cpu', 'Dual core 2.4 GHz, 16 GB RAM, 256 GB HD'),
 ('11', 'monitor', 'HP V197 18.5-inch'),
 ('11', 'keyboard', 'HP Ultrathin Wireless Keyboard'),
 ('11', 'phone', 'Cisco Phone IP 7960G/7940G'),
 ('11', 'chair', '817L Kare Ergonomic Office Chair'),
 ('11', 'mouse', 'HP USB 2 Button Optical Mouse'),
 ('11', 'drawer', 'Simple drawer'),
 ('12', 'desk', 'Simple desk'),
 ('12', 'cpu', 'Dual core 2.4 GHz, 16 GB RAM, 256 GB HD'),
 ('12', 'monitor', 'HP V197 18.5-inch'),
 ('12', 'keyboard', 'HP Ultrathin Wireless Keyboard'),
 ('12', 'chair', '817L Kare Ergonomic Office Chair'),
 ('12', 'mouse', 'HP USB 2 Button Optical Mouse'),
 ('12', 'drawer', 'Simple drawer');
